### ISSUE TITLE
Negatives

### ISSUE THREAD

**Issue by vekett** [TheMachinumps/Cookie_Clicker_3DS#1]
After upgrading the Cookies Per Second upgrade a few times, it goes to -2.

**Comment by GabrielRRussell** [comment]
Can you leave more specifics? Cookie count, costs, how fast you do this. I can take a look through the source and fix this if you give me more info.

Also, what goes to -2? The cookies? Or CPS?

**Comment by AntiMach** [comment]
That is something also known as an integer overflow. At the time, I didn't know of any other way of creating variables, so I used 32-bit integers. Once the integers reach a number higher than 2,147,483,647, the value overflows to -2,147,483,648. I can't really fix this now since I don't have devkitpro to build the application and test it...

**Comment by GabrielRRussell** [comment]
Can't you use a char? Or if you still want an integer, unsigned long long?

**Comment by AntiMach** [comment]
Now with the new, and revamped version, this bug no longer occurs!
